trainer: adsorbdiff.trainers.meanflow_trainer.MeanFlowTrainer

dataset:
  - src: train_split
    normalize_labels: False
  - src: val_split
    normalize_labels: False
logger:
  name: wandb
  project: ads_COM_diff


task:
  dataset: lmdb
  train_on_free_atoms: True
  eval_on_free_atoms: True
  relaxation_steps: 100
  relaxation_fmax: 0.01
  relax_dataset:
        src: val_nonrelaxed_update
  relax_opt:
        maxstep: 0.04
        memory: 50
        damping: 1.0
        alpha: 70.0
        cfg_scale: 2.0
        traj_dir: relax_opt
  primary_metric: loss
hide_eval_progressbar: False


model:
  name: adsorbdiff.models.equiformer_v2.equiformer_v2_denoising.EquiformerV2S_OC20_DenoisingPos

  use_pbc:                  True
  regress_forces:           True
  otf_graph:                True
  max_neighbors:            20
  max_radius:               12.0
  max_num_elements:         120

  num_layers:               8
  sphere_channels:          128
  attn_hidden_channels:     64
  num_heads:                8
  attn_alpha_channels:      64
  attn_value_channels:      16
  ffn_hidden_channels:      128
  norm_type:                'layer_norm_sh'

  lmax_list:                [4]
  mmax_list:                [2]
  grid_resolution:          18

  num_sphere_samples:       128

  edge_channels:            128
  use_atom_edge_embedding:  True
  distance_function:        'gaussian'
  num_distance_basis:       512

  attn_activation:          'silu'
  use_s2_act_attn:          False
  ffn_activation:           'silu'
  use_gate_act:             False
  use_grid_mlp:             True

  alpha_drop:               0.1
  drop_path_rate:           0.05
  proj_drop:                0.0

  weight_init:              'uniform'
  so3_denoising:            True
  FOR_denoising:            True
  energy_encoding:          scalar

optim:
  batch_size:                  4
  eval_batch_size:              4
  grad_accumulation_steps:      1
  load_balancing: atoms
  num_workers: 1
  lr_initial:                   2.e-4

  optimizer: AdamW
  optimizer_params:
    weight_decay: 0.001
  scheduler: StepLR
  step_size: 3
  gamma: 0.95

  max_epochs: 300
  force_coefficient: 100
  energy_coefficient: 2
  clip_grad_norm: 100
  ema_decay: 0.999
  loss_energy: mae
  loss_force: l2mae

  eval_every: 10000
  checkpoint_every: 1000
  checkpoint_every_epoch: 5

  p_cfg: 0.2

  flow:
    nan_weight_debug: false
    monitor_interval: 0
    type: fm
    fm_regression: velocity
    path: rectified
    time_sampl: uniform
    tr_sigma: 3
    tr_sigma_z_scale: 0
    allow_z: false
    rot_sigma: 1
    tr_clip: 15
    rot_clip: 5
    grad_norm_guard: 5000000
    write_every: 10
    output_clip:
      translation: 40
      rotation: 10
